name: unbeliever
version: 0.11.3.1
synopsis: Opinionated Haskell Interoperability
description: |
  A library to help build command-line programs, both tools and
  longer-running daemons. Its @Program@ type provides unified ouptut &
  logging, command-line option parsing, exception handling, and a place to
  put top-level application state. There's also an underlying @Rope@ text
  type built on a finger tree of UTF-8 fragments along with conveniences
  for pretty printing and colourizing terminal output.
  
  A description of this package, a list of features, and some background
  to its design is contained in the
  <https://github.com/aesiniath/unbeliever/blob/master/README.markdown README>
  on GitHub.
  
  Useful starting points in the documentation are
  <../core-program/docs/Core-Program-Execute.html Core.Program.Execute> and
  <../core-text/docs/Core-Text-Rope.html Core.Text.Rope>.
  
  An ancillary purpose of this library is to facilitate interoperability
  between different package families and ecosystems. Having a single
  batteries-included package (as was originally the case) made using it
  easier, but the resulting dependency footprint was considerable and
  growing. The code is thus now spread across several packages:
  
  * __core-text__
  * __core-data__
  * __core-program__
  * __core-telemetry__
  * __core-webserver-warp__
  * __core-webservver-servant__
  
  with more forthcoming as we continue to add convenince and
  interoperability wrappers around streaming, webservers, and database
  access patterns.

stability: stable
license: MIT
license-file: LICENSE
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2018-2022 Athae Eredh Siniath and Others
tested-with: GHC == 9.2.4
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: aesiniath/unbeliever

dependencies:
 - base >= 4.11 && < 5
 - core-text
 - core-data
 - core-program

executables:
  snippet:
    dependencies:
    - bytestring
    - effectful
    - effectful-core
    - core-effect-effectful
    ghc-options:
     - -threaded
    source-dirs:
     - tests
    main: EffectSnippet.hs
    other-modules: []

  experiment:
    buildable: false
    dependencies:
     - bytestring
     - prettyprinter
     - unordered-containers
    ghc-options:
     - -threaded
    source-dirs:
     - tests
    main: SimpleExperiment.hs
    other-modules: []

  webserver:
    buildable: false
    dependencies:
    - bytestring
    - bytestring-trie
    - core-telemetry
    - core-webserver-warp
    - http-types
    - wai
    ghc-options:
     - -threaded
    source-dirs:
     - tests
    main: WarpSnippet.hs
    other-modules: []

tests:
  check:
    dependencies:
    - aeson
    - bytestring
    - bytestring-trie
    - fingertree
    - hashable
    - hspec
    - network-info
    - prettyprinter
    - QuickCheck
    - safe-exceptions
    - scientific
    - stm
    - text
    - text-short
    - time
    - unordered-containers
    - wai
    - core-text
    - core-data
    - core-program
    - core-telemetry
    - core-webserver-servant
    - core-webserver-warp

    ghc-options: -threaded
    source-dirs:
     - tests
    main: TestSuite.hs
    other-modules:
     - CheckArgumentsParsing
     - CheckBytesBehaviour
     - CheckContainerBehaviour
     - CheckExternalizing
     - CheckJsonWrapper
     - CheckProgramMonad
     - CheckRopeBehaviour
     - CheckTelemetryMachinery
     - CheckTimeStamp
     - CheckWebserverIntegration

benchmarks:
  performance:
    dependencies:
     - bytestring
     - gauge
     - text
    ghc-options: -threaded
    source-dirs:
     - bench
    main: GeneralPerformance.hs 
    other-modules: []
