resolver: nightly-2022-08-15
compiler: ghc-9.2.2
packages:
 - ./core-data
 - ./core-text
 - ./core-program
 - ./core-telemetry
 - ./core-webserver-servant
 - ./core-webserver-warp
 - .
extra-deps: []

