resolver: lts-20.18
compiler: ghc-9.2.7
packages:
 - ./core-data
 - ./core-effect-effectful
 - ./core-text
 - ./core-program
 - ./core-telemetry
 - ./core-webserver-servant
 - ./core-webserver-warp
 - .
extra-deps: []
