resolver: lts-18.28
packages:
 - ./core-data
 - ./core-text
 - ./core-persistence-hasql
 - ./core-program
 - ./core-telemetry
 - ./core-webserver-servant
 - ./core-webserver-warp
 - .
extra-deps:
 - semialign-1.2
 - time-compat-1.9.6.1
 - hashable-1.3.5.0
