resolver: lts-21.25
compiler: ghc-9.4.8
packages:
 - ./core-data
 - ./core-effect-effectful
 - ./core-text
 - ./core-program
 - ./core-telemetry
 - ./core-webserver-servant
 - ./core-webserver-warp
 - .
extra-deps: []
