resolver: lts-21.9
compiler: ghc-9.4.6
packages:
- ./core-data
- ./core-effect-effectful
- ./core-text
- ./core-program
- ./core-telemetry
- ./core-webserver-servant
- ./core-webserver-warp
- .
extra-deps:
- githash-0.1.7.0
