resolver: lts-22.38
compiler: ghc-9.6.6
packages:
 - ./core-data
 - ./core-text
 - ./core-program
 - ./core-telemetry
 - ./core-webserver-servant
 - ./core-webserver-warp
 - .
extra-deps: []

ghc-options:
  HsOpenSSL: -optc=-Wno-incompatible-pointer-types
