resolver: lts-20.8
compiler: ghc-9.2.4
packages:
 - ./core-data
 - ./core-effect-effectful
 - ./core-text
 - ./core-persistence-hasql
 - ./core-program
 - ./core-telemetry
 - ./core-webserver-servant
 - ./core-webserver-warp
 - .
extra-deps: []
