#!/bin/sh

set -x

ROOTDIR=`stack path --local-install-root`
DISTDIR=`stack path --dist-dir`

link () {
	NAME="$2"
	ORIGIN="$1"

	if [ -L ./${NAME} ] ; then
		rm -f ./${NAME}
	fi
	if [ -f ./${NAME} ] ; then
		exit 1
	fi
	ln -s ${ORIGIN} ${NAME}
}

# symlink a "executable" binary
e () {
	NAME="$1"
	link "${ROOTDIR}/bin/${NAME}" "${NAME}"
}

# symlink a "test-suite" binary
t () {
	NAME="$1"
	link "${DISTDIR}/build/${NAME}/${NAME}" "${NAME}"
}


# main
e experiment
e snippet
t check


