name: core-effect-effectful
version: 0.0.0.1
synopsis: Interoperability with the Effectful effects library
description: |
  This is part of a library to help build command-line programs, both tools and
  longer-running daemons.
  
  This package adds wrappers around the __effectful__ library, providing an
  implmentation of a ProgramE effect wrapping the Program τ monad from
  __core-program__.

stability: experimental
license: MIT
license-file: LICENSE
author: Juan Raphael Diaz Simões <juanrapha@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2023- Athae Eredh Siniath and Others
tested-with: GHC == 9.2.4
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: aesiniath/unbeliever
  
dependencies:
 - async
 - base >= 4.11 && < 5
 - core-data
 - core-program >= 0.6.1
 - core-telemetry >= 0.2.7
 - core-text
 - effectful-core
 - unliftio-core

library:
  dependencies: []
  source-dirs: lib
  exposed-modules:
   - Core.Effect.Effectful
  other-modules: []
