name: core-webserver-warp
version: 0.1.1.0
synopsis: Interoperability with Wai/Warp
description: |
  This is part of a library to help build command-line programs, both tools and
  longer-running daemons.
  
  This package in particular adds wrappers around the __wai__ (Web Application
  Interface) and __warp__ (Web Server) to facilitate integrating this commonly
  used webserver combination with the Program monad from __core-program__.

stability: experimental
license: MIT
license-file: LICENSE
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2021-2022 Athae Eredh Siniath and Others
tested-with: GHC == 8.10.7
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: aesiniath/unbeliever
  
dependencies:
 - async
 - base >= 4.11 && < 5
 - bytestring
 - core-data
 - core-program
 - core-telemetry >= 0.1.8
 - core-text
 - http-types
 - http2
 - mtl
 - safe-exceptions
 - vault
 - wai
 - warp

library:
  dependencies: []
  source-dirs: lib
  exposed-modules:
   - Core.Webserver.Warp
  other-modules: []
