name: core-program
version: 0.4.3.0
synopsis: Opinionated Haskell Interoperability
description: |
  A library to help build command-line programs, both tools and
  longer-running daemons.
  
  A description of this package, a list of features, and some background
  to its design is contained in the
  <https://github.com/aesiniath/unbeliever/blob/master/README.markdown README>
  on GitHub.
  
  See "Core.Program.Execute" to get started.

stability: stable
license: MIT
license-file: LICENSE
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2018-2022 Athae Eredh Siniath and Others
tested-with: GHC == 8.10.7
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: aesiniath/unbeliever

dependencies:
 - base >= 4.11 && < 5
 - bytestring
 - hashable >= 1.2
 - prettyprinter >= 1.6.2
 - template-haskell >= 2.14 && < 3
 - text
 - text-short
 - typed-process

library:
  dependencies:
   - async
   - core-text >= 0.3.4.0
   - core-data >= 0.2.1.11
   - chronologique
   - directory
   - exceptions
   - filepath
   - fsnotify
   - hourglass
   - mtl
   - safe-exceptions
   - stm
   - terminal-size
   - transformers
   - unix
  source-dirs: lib
  exposed-modules:
   - Core.Program
   - Core.Program.Arguments
   - Core.Program.Context
   - Core.Program.Execute
   - Core.Program.Logging
   - Core.Program.Metadata
   - Core.Program.Notify
   - Core.Program.Threads
   - Core.Program.Unlift
   - Core.System
   - Core.System.Base
   - Core.System.External
   - Core.System.Pretty
  other-modules:
   - Core.Program.Signal
