name: core-data
version: 0.3.2.2
synopsis: Convenience wrappers around common data structures and encodings
description: |
  Wrappers around common data structures and encodings.

  This is part of a library intended to ease interoperability and assist in
  building command-line programs, both tools and longer-running daemons.
  A list of features and some background to the library's design is contained
  in the
  <https://github.com/aesiniath/unbeliever/blob/master/README.markdown README>
  on GitHub.

stability: stable
license: MIT
license-file: LICENSE
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2018-2022 Athae Eredh Siniath and Others
tested-with: GHC == 8.10.7
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: aesiniath/unbeliever

dependencies:
 - aeson >= 1.5 && < 2 || >= 2.0.1
 - base >= 4.11 && < 5
 - bytestring
 - containers
 - hashable >= 1.2
 - prettyprinter >= 1.6.2
 - scientific
 - text
 - unordered-containers
 - vector
 - core-text >= 0.3.7

library:
  source-dirs: lib
  exposed-modules:
   - Core.Data
   - Core.Data.Structures
   - Core.Encoding
   - Core.Encoding.Json
  other-modules: []

